version: '3'
services:
  db:
    restart: always
    image: postgres:16-alpine
    shm_size: 256mb
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=pool
    ports:
      - "5432:5432"
    command: |
        postgres
          -c shared_preload_libraries=pg_stat_statements
          -c pg_stat_statements.track=all
          -c max_connections=200
          -c shared_buffers=256MB
          -c effective_cache_size=8GB
          -c work_mem=16MB
          -c maintenance_work_mem=128MB
          -c min_wal_size=128MB
          -c max_wal_size=2GB
          -c checkpoint_completion_target=0.9
          -c wal_buffers=16MB
          -c default_statistics_target=100
          -c timezone=UTC